#! /bin/sh

chosen=$(printf "Power Off\nRestart\nLock" | rofi -dmenu -i -p "Danial Machine State")


case "$chosen" in 
    "Power Off") poweroff ;;
    "Restart") reboot ;;
    "Lock") slock ;;
    *) exit 1 ;;
esac
